### ISSUE TITLE
Git Powered CMS

### ISSUE THREAD

**Issue by kirtan403** [cloudflare/production-saas#15]
Full SaaS application running on Cloudflare is great. But are there any plans to build a CMS that commits to git to keep the content in the repo only and build with the CI/CD on Cloudflare?

Also if the website content is stored in the KV and a static JAMSTACK site is built, direct way to access KV from the API in the build phase, and CMS can direct save in KV would be great.

**Comment by lukeed** [comment]
This is more of a static-site generator feature and not something a SaaS would offer. With git-based systems, there's no reason to use anything over the network since the entire content & assets are already available and managed locally.

Your second paragraph is definitely possible and is the intended usage. Any existing jamstack site would be making API requests for its content at build-time. The requests made are determined entirely by the user, so they have full control. The usage will match existing headless CMS platforms (eg, Sanity or Contentful) if you're familiar with them 

Closing, but please let me know if I misunderstood anything!

**Comment by kirtan403** [comment]
Got your point. I was asking if we could build something that will store data in KV instead of the Sanity... So your CMS would be saving changes in the Workers KV (instead of Sanity) and using KV API to get data at build time

**Comment by lukeed** [comment]
Correct, data is stored in KV.
But at build-time, you'll make HTTP calls for your data from the deployed demo (or your own hosted version). This is common to all headless CMS integrations.

**Comment by kirtan403** [comment]
Correct, that's great. Looking forward for the initial version.
